name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Cancel in-progress runs when a new workflow is triggered
concurrency:
  group: "arraylink-deploy"
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: arraylink
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Prepare deployment package
        run: |
          # Create deployment directory
          mkdir -p deployment
          # Copy server files first
          cp server.js web.config package.json package-lock.json deployment/
          # Install production dependencies in deployment folder
          cd deployment
          npm install --production
          # Create build directory and copy build files
          mkdir -p build
          cp -r ../build/* build/
        
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
          package: deployment 