name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Cancel in-progress runs when a new workflow is triggered
concurrency:
  group: "arraylink-deploy"
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: arraylink
  NODE_VERSION: '20.x'
  BUILD_VERSION: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Prepare deployment package
        run: |
          # Create deployment directory
          mkdir -p deployment
          # Copy server files first
          cp server.js web.config package.json package-lock.json deployment/
          # Install production dependencies in deployment folder
          cd deployment
          npm install --production
          # Create build directory and copy build files
          mkdir -p build
          cp -r ../build/* build/
          # Save build version for runtime awareness
          echo "BUILD_VERSION=${BUILD_VERSION}" >> .env
      
      - name: Deploy to Azure Web App
        id: deploy1
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BAY_01A84F80F }}
          package: deployment

      - name: Wait before retry
        if: failure()
        run: |
          echo "First deploy failed, waiting 30s before retry..."
          sleep 30

      - name: Deploy to Azure Web App (retry)
        if: failure()
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BAY_01A84F80F }}
          package: deployment 
